# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gptc < Formula
  desc "Supercharge your CLI with the power of OpenAI's GPT model (and other models too!)"
  homepage "https://github.com/junyu-w/gptc"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/junyu-w/gptc/releases/download/v1.0.0/gptc_Darwin_arm64.tar.gz"
      sha256 "cccbdf2ce4ccd0ead2409712c6ca76075b0e178912de6dade8417e73d9b61860"

      def install
        bin.install "gptc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/junyu-w/gptc/releases/download/v1.0.0/gptc_Darwin_x86_64.tar.gz"
      sha256 "e3e6bac7cf535b545a20e2a69f76de6c2d66028eb4fdaecd7bc6bf4564741a34"

      def install
        bin.install "gptc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/junyu-w/gptc/releases/download/v1.0.0/gptc_Linux_arm64.tar.gz"
      sha256 "2d92e9a522089f05e50794cd7a36b249f6f50aba8b989539cab735e1f5f222ee"

      def install
        bin.install "gptc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/junyu-w/gptc/releases/download/v1.0.0/gptc_Linux_x86_64.tar.gz"
      sha256 "432084645c372830be0ebd8dc4437ac37d35a954951fea8c10aac3f086d2a270"

      def install
        bin.install "gptc"
      end
    end
  end
end
